---
###############################
# Upload/Deploy Template
###############################
rhevm_username: admin@internal
rhevm_password: smartvm
export_datastore: export

# Template:
appliance_template: http://manageiq.org/download/manageiq-ovirt-capablanca-2.ova


###############################
# Collectd Configuration Items
###############################
# Apache Monitoring needs improvement to prevent wrecking standard http://(ip addr)/ access
apache_monitoring: false
collectd_interval: 10
graphite_host: 1.1.1.1
graphite_prefix: manageiq


###############################
# CFME items
###############################
setup_vmdb_region: 0
use_separate_vmdb_disk: true
vmdb_disk: /dev/vdb
vmdb_password: smartvm
# Use false if patching before init-vmdb playbook/role
proctitle_restart: false

chrony_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org


###############################
# CFME 2nd interface ip address
###############################
# Map inventory to ip addresses
ip_addresses:
  inventory_hostname1:
    ipaddr: 172.16.10.10
    netmask: 255.255.255.0
  inventory_hostname2:
    ipaddr: 172.16.10.11
    netmask: 255.255.255.0


###############################
# Repos
###############################
repos:
  rhel7:
    baseurl: http://download.example.com/repos/RHEL-7/7.2/Server/$basearch/os/
  rhel7z:
    baseurl: http://download.example.com/repos/rhel-7.2-z-candidate/x86_64/
  rhscl7:
    baseurl: http://download.example.com/repos/RHSCL-2.0-RHEL-6-Alpha-1.8/compose/Server/x86_64/os/
  rhel7_optional:
    baseurl: http://download.example.com/repos/RHEL-7/7.2/Server-optional/$basearch/os/


###############################
# RPMs:
###############################
epel7_rpm: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
