---
#
# Install/Configure Carbon and Graphite
#

- name: Check for epel
  shell: rpm -qa | grep -q epel-release
  ignore_errors: true
  register: epel_installed

- name: Install epel repo (rhel7)
  command: rpm -ivh {{ epel7_rpm }}
  when: (epel_installed.rc != 0) and (ansible_os_family == "RedHat" and ansible_distribution_version|int == 7)

- name: Install epel repo (rhel6)
  command: rpm -ivh {{ epel6_rpm }}
  when: (epel_installed.rc != 0) and (ansible_os_family == "RedHat" and ansible_distribution_version|int == 6)

- name: Install carbon/graphite rpms
  yum: name={{ item }} state=present
  with_items:
    - graphite-web
    - python-carbon
    - expect

- name: Check for graphite.db sqlite
  shell: ls /var/lib/graphite-web/graphite.db
  ignore_errors: true
  register: graphite_db_installed

- name: Copy setup-graphite-db.exp
  template:
    src=setup-graphite-db.exp.j2
    dest=/root/setup-graphite-db.exp
    owner=root
    group=root
    mode=0755

- name: Create initial graphite db
  shell: "/root/setup-graphite-db.exp {{ graphite_username }} {{ graphite_password }} && chown apache:apache /var/lib/graphite-web/graphite.db"
  when: graphite_db_installed.rc != 0

- name: Setup apache graphite-web config
  template:
    src=graphite-web.conf.j2
    dest=/etc/httpd/conf.d/graphite-web.conf
    owner=root
    group=root
    mode=0644

- name: Add firewall rules for carbon-cache and graphite (rhel7)
  command: "{{ item }}"
  with_items:
    - "firewall-cmd --zone={{firewall_zone}} --add-port=2003/tcp --permanent"
    - "firewall-cmd --zone={{firewall_zone}} --add-port={{graphite_port}}/tcp --permanent"
    - firewall-cmd --reload
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int == 7

- name:  Add firewall rules for carbon-cache and graphite (rhel6)
  iptables: chain=INPUT protocol=tcp destination_port={{item}}
  with_items:
    - 2003
    - "{{graphite_port}}"
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int == 6

- name: Restart apache
  service: name=httpd state=restarted enabled=true
  ignore_errors: true

- name: Ensure carbon-cache service is started and enabled
  service: name=carbon-cache state=started enabled=true

- name: Copy carbon storage-schemas.conf config
  copy:
    src=storage-schemas.conf
    dest=/etc/carbon/storage-schemas.conf
    owner=root
    group=root
    mode=0644

- name: Setup carbon config
  copy:
    src=carbon.conf
    dest=/etc/carbon/carbon.conf
    owner=root
    group=root
    mode=0644

- name: Stop carbon-cache
  service: name=carbon-cache state=stopped

- name: Remove initial set carbon storage due to sizing off initial config
  command: "rm -rf /var/lib/carbon/whispher/carbon"

- name: Restart carbon-cache
  service: name=carbon-cache state=restarted enabled=true

- name: Disable EPEL
  shell: rpm -e epel-release
  ignore_errors: true
