---
#
# Clean logs and restart CFME/ManageIQ Services
#

- hosts: cfme-vmdb,cfme-worker,cfme-all-in-one
  gather_facts: false
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - clean-logs
