---
#
# Setup chronyd service
#

- name: Ensure chrony is installed
  yum: name=chrony state=present

- name: Setup chrony config file
  template:
    src: chronyd.conf.j2
    dest: /etc/chrony.conf

- name: Restart chronyd
  service: name=chronyd enabled=true state=restarted
