---
#
# Patches files for statsd miqqueue publishing timing values
#

- name: Create patched files for statsd-miqqueue-patch
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - src: miq_queue.rb.patch.j2
      dest: /root/miq_queue.rb.patch
    - src: runner.rb.patch.j2
      dest: /root/runner.rb.patch

- name: Deploy patched files for statsd-miqqueue-patch
  patch:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: true
    backup: true
  when: is56 or is57 or is58
  with_items:
    - src: /root/miq_queue.rb.patch
      dest: /var/www/miq/vmdb/app/models/miq_queue.rb
    - src: /root/runner.rb.patch
      dest: /var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb
  notify:
    - restart evmserverd for statsd-miqqueue-patch
