---
#
# Playbook to install Grafana on the monitorhost
#

- hosts: monitorhost
  gather_facts: true
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - grafana
