---
#
# Playbook to install Carbon/Graphite on the monitorhost
#

- hosts: monitorhost
  gather_facts: false
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - hostname
    - repos
    - graphite
    - collectd-monitorhost
