---
#
# Playbook to set static interfaces on CFME/ManageIQ appliances
#

- hosts: cfme-vmdb, cfme-worker, cfme-all-in-one
  gather_facts: false
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - { role: config-interface, when: "{{appliances[inventory_hostname].interfaces|length}} > 0" }
