---
#
# Import a database playbook
#

- hosts: cfme-vmdb
  gather_facts: false
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - {role: database-import, when: "{{appliances[inventory_hostname].dbdump}} is defined" }
