---
#
# Playbook to setup database on appliances (Handles vmdb and worker appliances)
#

- hosts: cfme-vmdb, cfme-worker
  gather_facts: false
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - { role: init-vmdb, when: not isdeployed }
