---
#
# Post deployment of appliance automation
#

- hosts: cfme-vmdb
  gather_facts: false
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: smartvm
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - sshkey

- hosts: cfme-vmdb
  gather_facts: false
  remote_user: root
  vars:
    config_type: cfme-vmdb
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - hostname
    - repos
    - chronyd
    - { role: config-interface, when: "{{appliances[inventory_hostname].eth1}} is defined" }
    - proctitle-patch
    - init-vmdb
    - { role: collectd, when: (is55 or is56) }
