---
#
# Post deployment of appliance automation
#

- hosts: cfme-vmdb
  gather_facts: false
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: smartvm
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - sshkey

- hosts: cfme-vmdb
  gather_facts: true
  remote_user: root
  vars:
    config_type: cfme-vmdb
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - hostname
    - repos
    - { role: ntpd, when: (is54)}
    - { role: chronyd, when: (is55 or is56)}
    - { role: config-interface, when: "{{appliances[inventory_hostname].interfaces|length}} > 0" }
    - proctitle-patch
    - init-vmdb
    - collectd
    - { role: statsd-patch, when: "{{appliances[inventory_hostname].run_statsd}} == true"}
