---
#
# Playbook to apply patch for process titles on 5.5.x CFME appliances
#

- hosts: cfme-vmdb, cfme-worker, cfme-all-in-one
  gather_facts: false
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - { role: proctitle-patch, when: is55}
