---
#
# Playbook to add necessary repos to CFME/ManageIQ appliances
#

- hosts: cfme-vmdb, cfme-worker, cfme-all-in-one
  gather_facts: true
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - repos
