---
#
# Playbook to add current user's ssh key to all inventory hosts
#

- hosts: all
  gather_facts: false
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: smartvm
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - sshkey
