---
#
# Playbook to setup chronyd/ntpd for CFME/Miq appliances
#

- hosts: cfme-vmdb,cfme,cfme-all-in-one
  gather_facts: false
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - { role: ntpd, when: (is54)}
    - { role: chronyd, when: (is55 or is56)}
