---
#
# Setup ntpd service
#

- name: Set up ntp config file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: Start ntpd
  service: name={{item}} state=started enabled=true
  with_items:
    - ntpd
