---
#
# Configure second interface with static ip address
#

- name: Deploy static ifcfg
  template:
    src=ifcfg.j2
    dest=/etc/sysconfig/network-scripts/ifcfg-{{item.name}}
    owner=root
    group=root
    mode=0644
  with_items: "{{appliances[inventory_hostname].interfaces}}"

- name: Bounce interface
  shell: "ifdown {{item.name}}; ifup {{item.name}}"
  with_items: "{{appliances[inventory_hostname].interfaces}}"
